# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 043825640db3949243fbae847615c818e46684f5f5e5d87d4fc91892aba957a0cbcba3cbee5e88a214d79d0e575b878abed16e89f7c84d7794318ddee1f3cb9b

test:
  secret_key_base: 591c03992bdece4c62c8ce46e0293c2489e04ff9a2a241c0a7511cb93a80a7848ad0179efa78fd848fac7d4d207f8450b0842b7aef3481b2d3f8c53f096917de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
